services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:4000"
    environment:
      MONGO_URI: mongodb+srv://hoangnhat:007007007@cluster0.zpzh5.mongodb.net
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    ports:
      - "5174:80"
    env_file:
      - ./admin/.env

volumes:
  mongo-data:
